# Build settings
# permalink: /blog/:year/:title/
permalink: /showcases/:year/:title/
markdown: kramdown
highlighter: pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

paginate: 10
paginate_path: "/showcases/page/:num/"
comments: false

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Kevin Lin
description: "Full Stack Java Angular AngularJS Developer"
keywords: "Full Stack, Java, Angular, AngularJS, Developer, Software Engineer, Kevin Lin, Kevin, resume"
url: https://kevinlinxp.github.io
baseurl: ""

google_analytics: UA-52446115-1
repo: https://github.com/kevinlinxp
disqus_shortname: "kevinlinxp"
disqus_site_shortname: "kevinlinxp"

# Author settings
author:
  name: Kevin Lin
  job: Full Stack Java Developer
  bio: "I regard building high-quality and valuable software systems as the very essence of my career, and I love to combine all sorts of suitable technologies - traditional or cutting-edge - to realise fantastic ideas or to take existing projects to the next level."
  thumb: /images/kevinlin@hahndorf.jpeg
  email: kevinlinxp@gmail.com
  url: https://kevinlinxp.github.io
  github: https://github.com/kevinlinxp
  linkedin: https://linkedin.com/in/kevinlinxp

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
