# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Kevin Lin
description: "Full Stack Java Angular AngularJS Developer"
keywords: "Full Stack, Java, Angular, AngularJS, Developer, Software Engineer, Kevin Lin, Kevin, resume"
url: https://kevinlinxp.github.io
baseurl: ""

google_analytics: UA-52446115-1
repo: https://github.com/kevinlinxp
disqus_shortname: "kevinlinxp"
disqus_site_shortname: "kevinlinxp"

# Author settings
author:
  name: Kevin Lin
  job: Full Stack Java Developer
  bio: "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb: /images/author.jpg
  email: kevinlinxp@gmail.com
  url: https://kevinlinxp.github.io
  github: https://github.com/kevinlinxp
  linkedin: https://www.linkedin.com/in/kevin-lin-9b016571/

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
